// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EaJu54sNwrdU1tFzscMN_xu71rfySMM',
    appId: '1:50273410828:web:eb56e1ec336ba1bdbb3329',
    messagingSenderId: '50273410828',
    projectId: 'chattapp-1488d',
    authDomain: 'chattapp-1488d.firebaseapp.com',
    storageBucket: 'chattapp-1488d.appspot.com',
    measurementId: 'G-M2EE5T471N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75-ETqpH-1smMgtrjVCYdscPA92NdGHw',
    appId: '1:50273410828:android:c5d89f938ca49678bb3329',
    messagingSenderId: '50273410828',
    projectId: 'chattapp-1488d',
    storageBucket: 'chattapp-1488d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVPk8ZJYTuu62a6R7IwACfDLf1dz15nw',
    appId: '1:50273410828:ios:9fcc0f6f6ab66681bb3329',
    messagingSenderId: '50273410828',
    projectId: 'chattapp-1488d',
    storageBucket: 'chattapp-1488d.appspot.com',
    iosBundleId: 'com.example.chattapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuVPk8ZJYTuu62a6R7IwACfDLf1dz15nw',
    appId: '1:50273410828:ios:9fcc0f6f6ab66681bb3329',
    messagingSenderId: '50273410828',
    projectId: 'chattapp-1488d',
    storageBucket: 'chattapp-1488d.appspot.com',
    iosBundleId: 'com.example.chattapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7EaJu54sNwrdU1tFzscMN_xu71rfySMM',
    appId: '1:50273410828:web:fdf0c2f2ec6be63cbb3329',
    messagingSenderId: '50273410828',
    projectId: 'chattapp-1488d',
    authDomain: 'chattapp-1488d.firebaseapp.com',
    storageBucket: 'chattapp-1488d.appspot.com',
    measurementId: 'G-FVP8WDJFYH',
  );
}
